### PR TITLE
Initial sketch for working code for Req-7

### PR DESCRIPTION
**Pull request by TPolzer**
As I tried to explain last meeting, tracking touched files over history
is nontrivial. It requires at the least to look at history as a graph
instead of a linear view. I implemented this by using the Functional
Java library (that one could argue is not very well documented and quite
big), that gives us a lazy Tree<A>. I now implemented a view on version
history as a Tree<String> that simply holds the commit ids.
For computing the set of touched files per requirement and vice versa I
now turn to the immutable TreeMap / Set types also from the Functional
Java library, that also happen to give us a reasonably intuitive way to
handle looking at multiple HEADS (i.e. branches).
This admittedly has some drawbacks:
- Functional Java data structures are not easily serialized
- we pull in a large library
If you happen to have an elegant solution that somehow works around
those issues let us discuss this, also I think somebody should have a
look at the cli 'git blame' tool, because it has to do similar
bookkeeping.

If nobody has a _working_ better idea until tomorrow 12 a.m. I will merge this.

Gayathery, could you please add the app for Req-8 and do some more tests (especially with merges that should in _theory_ now work)

### CODE REVIEW

**Comment by gayathery** [comment]
I saw the implementation and its nice that you put this effort. But I have the following questions.

Before that I tell you my understanding of your code.

I understood that you form a tree in which the commit of each file for an requirement is a branch in your tree. and my questions are

1. Is it really necessary to calculate so much to get this hierarchy(cant it be achieved by chronological information)

2. your implemenation will really be a performance overhead, because we are speaking about more than 10000 requirements and many files being changed for each requirement over time and also we are planning to have some data from the database which all together will create a big performance bottle neck

3. Another important overhead would be to maintain this tree to have always the latest data. 

I am overall sckeptical about this approach and I fear this is also not a real requirement from our industry partner. and i also feel that a hierarchy of changes pertaining to each file can be achieved just by storing chronological information

And regarding Req 8, I thought you were working on this because i took responsibility on Req 7. If not I can work on this and add the app too

**Comment by gayathery** [comment]
I think you should wait before proceeding with your commit, because the code you have implemented is not required for implementing our requirements

**Comment by TPolzer** [comment]
> 1. Is it really necessary to calculate so much to get this hierarchy(cant it be achieved by chronological information)

Yes it is really necessary to interpret the history graph as a graph, otherwise you will lose information and that will lead to problems.
> 2. your implemenation will really be a performance overhead [...]

I think you have a wrong impression here. The way the implementation works is actually faster than the code that is in master right now. The real problem is not performance but memory overhead, because the way it works now, all information (about the whole repository) has to be kept in memory, but that is really a nonissue because 1. nearly nothing we do right now acts in a streaming manner and 2. the industry partner agreed that enormous repositories (think 100000+ commits) are not important right now.

> 3. Another important overhead would be to maintain this tree to have always the latest data.

No, I maintain a (actually two) Map(s) commitid -> information, all bookkeeping is already implemented, please read _and understand_ the code (yes I should document it a little more, but I do not have the time right now, sorry).

> [...]  i also feel that a hierarchy of changes pertaining to each file can be achieved just by storing chronological information

This is the important bit: Your feeling is wrong! Storing just chronological information is not enough, the graph has to be preserved.

> And regarding Req 8, I thought you were working on this because i took responsibility on Req 7. If not I can work on this and add the app too

I am quite short on time right now, and the functionality in VcsInterpreter is already there, you just have to query commitToFileToReqs.

> I think you should wait before proceeding with your commit, because the code you have implemented is not required for implementing our requirements

As already said, it _is_ required, otherwise we need an alternative (that is not wrong like the current master branch).

**Comment by TPolzer** [comment]
A little bit more detail on the bookkeeping part:
For normal commits all it takes is an incremental entry (in O(log(n))), that trivial optimization was actually missing, I put it there right now.
Merges are in O(n*log(n)) right now, where n is max(files,requirements), but I have yet to find a better way, and merges are a minority.

**Comment by gayathery** [comment]
"This is the important bit: Your feeling is wrong! Storing just chronological information is not enough, the graph has to be preserved."

I am not able to understand what you are trying to preserve in graph...if you take for example for Req-1, FileA is changed multiple times and commited multiple times. our requirement here is to find the changed data in FileA for this requirement...indirectly it means the difference that happened to this file in each commit...lets say for FileA

Commit 1 for Req-1 - ChangedDataX
Commit 2 for Req-1 - ChangedDataY
Commit 3 for Req-1 - ChangedDataZ

Here our requirement is to find for Req-1 that FileA is changed and the changed data are ChangedDataX, ChangedDataY and ChangedDataZ.
And my current implementation provides information that for Req-1
FileA is changed in Commit 1,2 and 3...and I already know how to take the changed data for these commits...so that all is our requirement...and so i think the new code is not necessary.
If you still think that your code must be commited, do not alter existing implementation in master, instead add is a separate functionality...but from my point of view the new code is not necessary.
Also please explain me why the current method wont work and give me an example where the current implementation wont work

**Comment by TPolzer** [comment]
Look at the test2/git test repository that I pushed to the Req7 branch. E.g. query it for requirement 4, the result should be "file5", not "file1 MODIFIED file1 c9397748f063d993448faf6e55d05d2f565a539d". 

I am really getting tired of arguing stuff to you that we discussed in quite some length already...

**Comment by gayathery** [comment]
can you tell me the history of file1 and file5 in this test repostitory because i am not able to visualize in GitClient

**Comment by gayathery** [comment]
I saw the history now...For Req-4 you added File1 and for Req-8 you renamed File1 to File5 and as per your coding you will return for Req-4 that File5 was changed. But if you map File5 to Req-4 that is not correct because then you lose the information about File1 which is the key to find the changed information for Req-4... and in fact the renaming of the file itself is meant for Req-8 and not for Req-4. I understand that the user will not see the file since it is renamed...but this has to be cared only when showing in the UI and not internally

**Comment by TPolzer** [comment]
I can see now that you understood neither my code, nor the user story.

There is no information lost, and tracking information is not something that should be handled by the UI, but exactly what we wanted to achieve with this user story.

**Comment by gayathery** [comment]
when u return to the user File5 for Req-4, then obviously information about File1 is lost. we should tell the user about File1 and the difference in data that was made for the commit and then we need to specify that File1 is now renamed as File5. because the renaming itself was part of another requirement

**Comment by gayathery** [comment]
And also one more thing this changes to a file through the history can be got using PlotWalk which is much more easier to track the history of a file. so you can do a PlotWalk of the file after the commit under consideration and then we can get information about rename and deletion which we can report to the user

**Comment by TPolzer** [comment]
We do not want to implement a filtered 'git log', that is not the purpose of this user story (and a filtered view on the log is not useful).

**Comment by gayathery** [comment]
i did not mean to view it like that ...for example in your case we have to show the difference for File1 for Req-4 and also tell the user that the current file is File5 which was renamed later

you can use the following code for it to find the current state of the File1
path="File1"
 PlotCommitList<PlotLane> plotCommitList = new PlotCommitList<PlotLane>();
	    PlotWalk revWalk = new PlotWalk(repo);
 ObjectId rootId = repo.resolve("HEAD");
	        if (rootId != null) {
	            RevCommit root = revWalk.parseCommit(rootId);
	            revWalk.markStart(root);
	            revWalk.setTreeFilter(
	            	    AndTreeFilter.create(PathFilter.create(path), TreeFilter.ANY_DIFF));
	            plotCommitList.source(revWalk);
	            plotCommitList.fillTo(Integer.MAX_VALUE);

Here "plotCommitList" will give all the commits to the File1 and at the latest commit in this list contains the name of the file and it would be File5 and this can be given to the user. so we have info about File1, its changes for Req-4 and also its current name File5.. a small change in this would give for deletion of files too...these are the information that we need to give to the user

**Comment by gayathery** [comment]
Finally, i want to say if you want to merge your implementation, commit it without affecting the code i commited. later point of time we can decide which one is suitable for our project because you have your own view about the userstory and I have a different approach for this userstory

**Comment by TPolzer** [comment]
Please give an implementation that fulfills exactly the acceptance criteria for Req 7/8 or just accept my code. Just try to execute the code you just posted with "file4" on the test repository, you have a wrong view ;)

**Comment by gayathery** [comment]
I want to make one thing clear. I have a different approach for this user story and you have a different one. This is really subjective and you cannot justify I am wrong or correct. so you can proceed with your commit of your code but I just tell that not to change my code because my thoughts about the userstory is different and I am working towards the same final requirement

**Comment by TPolzer** [comment]
This is not subjective, I really have no idea anymore how to make that clear to you. Please try the examples that I gave with your code and you will see that they objectively do not conform with the acceptance criteria.

**Comment by gayathery** [comment]
and for your question about "file4" the code gives reference to Req-7.. but if u run the code for file3, it will also give the commit for file4 also since file3 was renamed to file4 later

**Comment by gayathery** [comment]
acceptance criteria says to list files that were changed for a requirement "Console that lists all source code files relating to a specific requirement" and the current implementation already lists it.there is NO specific requirement like to list "all CURRENT source code files pertaining to the requiorement"

**Comment by TPolzer** [comment]
The intent was impact analysis, the ONLY way this makes sense if it gives information on current files. Everything else is obviously garbage.

**Comment by gayathery** [comment]
everything else is not garbage. you have misunderstood the requirements. If a file is deleted it is still necessary to track the changes it had for a requirement before deletion. if you want we can ask these questions to industry partner

**Comment by yadimon** [comment]
dont know whats going on :), but in regars information save, i am sure, the industry partner, want all information.
queries like: show me by req-X:
- how man times req was committed, 
- how many files was changed
- how often
- what files was crossed by another req, and what reqs,
- how ofter there was collisions with other reqs by line codes  
.. etc ..
must be possible.

so we need everything :)

**Comment by gayathery** [comment]
Thats what my exact point is too..I agree with you.

**Comment by TPolzer** [comment]
I added some tests, performance is a little worse than I expected, maybe there are still some bugs in there, but for now it is the only implementation of this requirement that we have (even if you don't get it..).

**Pull request merged**
