### PR TITLE
Use maven as build system

### PR DESCRIPTION
**Pull request by TPolzer**
I find maven to be far more convenient than the eclipse build system, especially on the command line.

Please everybody have a look at this branch, so we can make an informed decision (if you guys all want to do eclipse I'll just close this branch).

If you do not know about maven, please have a look at this site: https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

### CODE REVIEW

**Comment by GnuTalux** [comment]
thanks for information.
I am using the IDEA-IDE from jetbrainz. therefore I would prefer a non-eclipse build system :)

**Comment by uv48uson** [comment]
Yes. As i red building the project with maven which easily handles all the dependencies would be a good idea. Nevertheless i still a bit worried whether maven would make the whole process more complicated by defining fixed workspace structures and so on. Ultimately i think we should try to work with maven.

**Comment by TPolzer** [comment]
As both people who worked on the code already (at least somewhat) agree, I'll merge this to master.

**Comment by gayathery** [comment]
there were some pom configuration linking to old junit, which i have adapted to one of the latest ones. because the old ones do not support annotations

**Pull request merged**
